version: '3.8'

services:
  php:
    image: alvicha/symfony-app:latest
    container_name: symfony_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./public/img:/var/www/html/public/img
    #   - .:/var/www/html
    depends_on:
      database:
        condition: service_healthy

  nginx:
    image: alvicha/symfony-nginx:latest
    container_name: symfony_nginx
    restart: always
    ports:
      - "80:80"  # Cambia el puerto 80 a 8080 en el host
    volumes:
      # - .:/var/www/html
      - ./public/img:/var/www/html/public/img
    depends_on:
      php:
        condition: service_started

  database:
    image: mysql:8.0
    container_name: symfony_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: FitnessRoot1234
      MYSQL_DATABASE: proyecto
      MYSQL_USER: fitness
      MYSQL_PASSWORD: fitness1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3

volumes:
  db_data:

# env_file:
#   - .env